### ISSUE TITLE
where is the code of depth attention

### ISSUE THREAD

**Issue by MrDec** [LiuYuML/Depth-Attention#1]
Thanks for your open-source code, It is a interseting work! howeve i cannot find the code of depth attention

**Comment by LiuYuML** [comment]
这位朋友看起来似乎想在自己的领域尝试一下我们的方法，方便加个联系方式不
邮箱
qq
微信
来一把跨领域合作？

**Comment by MrDec** [comment]
可以的，期待合作，dwwuestc@163.com
